FROM mysql:8.0

# 复制初始化脚本
COPY lucky-server/src/main/resources/schema.sql /docker-entrypoint-initdb.d/init.sql

# 设置字符集
CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
