FROM maven:3.9.6-eclipse-temurin-17-alpine AS builder
WORKDIR /app
COPY lucky-server/pom.xml .
RUN mvn dependency:go-offline -B
COPY lucky-server/src ./src
RUN mvn package -DskipTests -B

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
# 使用生产环境配置
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "app.jar"]
